// Planet CGI — Compositor: layer stack, blend modes, shader catalog with uniforms pipeline.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.

import { seededRandom } from "./rng";
import { LayerStack, BlendMath, ShaderCatalog } from "./modules";

export const SPEC = "Compositor: layer stack, blend modes, shader catalog with uniforms pipeline.";
export const MODULES = [{ id: "LayerStack", name: "Planet CGI :: LayerStack" }, { id: "BlendMath", name: "Planet CGI :: BlendMath" }, { id: "ShaderCatalog", name: "Planet CGI :: ShaderCatalog" }];
export { seededRandom };
export interface Node { id: string; position: number; parent: string | null; }
export class TransformGraph {
  private nodes = new Map<string, Node>();
  private nextId = 0;
  add(parent: string | null, position: number): string {
    const id = "n" + this.nextId++;
    this.nodes.set(id, { id, position, parent });
    return id;
  }
  worldPosition(id: string): number {
    let acc = 0;
    let cur: string | null = id;
    let guard = 0;
    while (cur && guard++ < 64) {
      const n = this.nodes.get(cur);
      if (!n) break;
      acc += n.position;
      cur = n.parent;
    }
    return acc;
  }
  depth(id: string): number {
    let d = 0;
    let cur = this.nodes.get(id)?.parent ?? null;
    while (cur && d < 64) { d++; cur = this.nodes.get(cur)?.parent ?? null; }
    return d;
  }
  nodeCount(): number { return this.nodes.size; }
  isAcyclic(): boolean {
    const visiting = new Set<string>();
    const visited = new Set<string>();
    for (const id of this.nodes.keys()) {
      if (this.acyclic(id, visiting, visited) === false) return false;
    }
    return true;
  }
  private acyclic(id: string, visiting: Set<string>, visited: Set<string>): boolean | void {
    if (visited.has(id)) return;
    if (visiting.has(id)) return false;
    visiting.add(id);
    const parent = this.nodes.get(id)?.parent ?? null;
    if (parent && this.acyclic(parent, visiting, visited) === false) return false;
    visiting.delete(id);
    visited.add(id);
  }
}
